### ISSUE TITLE
ConditionEnvironment directive in cloud-init service files is only supported for systemd >=246

### ISSUE THREAD

**Issue by anhvoms** [canonical/cloud-init#5604]
# Bug report
ConditionEnvironment directive was recently introduced to cloud-init service files ([link](https://github.com/canonical/cloud-init/commit/ec7dde8041d4023b09324e84abe37dc766ebbaf6)). This directive is only supported in systemd starting version 246. Ubuntu 20.04 cloud images only ship with systemd 245. This might cause some confusion for user when troubleshooting issues.

name 'ConditionEnvironment' in section 'Unit', ignoring.
[  106.354546] temp-vm-anhvo-eastus2-t20240812114016 systemd[1]: /lib/systemd/system/cloud-init-local.service:15: Unknown key name 'ConditionEnvironment' in section 'Unit', ignoring.
[  106.369179] temp-vm-anhvo-eastus2-t20240812114016 systemd[1]: /lib/systemd/system/cloud-config.service:8: Unknown key name 'ConditionEnvironment' in section 'Unit', ignoring.
[  106.370195] temp-vm-anhvo-eastus2-t20240812114016 systemd[1]: /lib/systemd/system/cloud-init.target:15: Unknown key name 'ConditionEnvironment' in section 'Unit', ignoring.
[  106.371090] temp-vm-anhvo-eastus2-t20240812114016 systemd[1]: /lib/systemd/system/cloud-final.service:9: Unknown key name 'ConditionEnvironment' in section 'Unit', ignoring.

## Steps to reproduce the problem
Deploy latest Ubuntu marketplace images on Azure then check journal log for entries by cloud-init services

## Environment details
- Cloud-init version: 24.1
- Operating System Distribution: Ubuntu 20.04
- Cloud provider, platform or installer type: Azure

## cloud-init logs
N/A

**Comment by blackboxsw** [comment]
Thanks @anhvoms for filing the bug and making cloud-init better.
I think this issue was also reported in #5402  and should be resolved by 7a2163c281511d7a03e0089931520fb92bcaa9ad and https://github.com/canonical/cloud-init/issues/5402 which is currently queued (and verified) for SRU into 20.04 as cloud-init version: 24.2. 

Our cloud-init SRU to Ubuntu Focal, Jammy and Noble is currently blocked on an unrelated [bug LP: 2075337 in python3-defaults](https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/2075337) which impacts cloud-init across deb package upgrade. Expectation is this should publish as fixed to focal this week.
Please re-open if this doesn't appear to address this problem.

**Comment by jazelenk** [comment]
I am still seeing this problem with the latest focal from the marketplace on Azure.

**Comment by TheRealFalcon** [comment]
> Expectation is this should publish as fixed to focal this week.

The fix has taken much longer to publish than anticipated, and so cloud-init is still blocked from releasing the latest version with this fix. Once released with the fix, `cloud-init --version` should be 24.3 or later.

**Comment by aciba90** [comment]
I think we meant 24.2 instead of 24.3.

**Comment by jazelenk** [comment]
Any update on this? We are still seeing this as of yesterday.

**Comment by jazelenk** [comment]
@TheRealFalcon @aciba90 any thoughts? I'm seeing this on the Azure marketplace image Canonical/0001-com-ubuntu-server-focal/20_04-lts/20.04.202410160

# uname -a
Linux can-01 5.15.0-1074-azure #83~20.04.1-Ubuntu SMP Fri Oct 4 21:49:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# cloud-init --version
/usr/bin/cloud-init 24.3.1-0ubuntu0~20.04.1

**Comment by TheRealFalcon** [comment]
@jazelenk , yes it looks like this is still present in 24.3.

**Comment by jazelenk** [comment]
Any update on this? Across a fleet, this is consuming a non-trival amount of storage for logs.

**Comment by aciba90** [comment]
No more updates. The issue is scheduled to be fixed in https://github.com/canonical/cloud-init/milestone/3, which is scheduled to be performed the 18th of November.

**Comment by TheRealFalcon** [comment]
Fixed in https://github.com/canonical/cloud-init/pull/5873 which will be available in the next SRU

**Comment by aciba90** [comment]
Closing per:

> Fixed in https://github.com/canonical/cloud-init/pull/5873 which will be available in the next SRU
